number1 = input("Which is the first natural number: ")
number2 = input("Which is the second natural number: ")
print("")
quotient = int(number1) // int(number2)
remnant = int(number1) % int(number2)
print("The quotient :" , quotient)
print("The remnant: " , remnant)
